export * from '../declarations/core-component';
// export * from './ComponentDecorators';
export * from './ComponentDecorators1';
export * from './EventDecorators';
export * from './EmitDecorators';
export * from './WatchDecorators';
export * from './MethodDecorators';
export * from './InjectDecorators';
export * from './ProvideDecorators';
export * from './PropDecorators';
export * from './StateDecorators';
