import TimePicker from './TimePicker';
export declare class DatePicker {
    private readonly option;
    private readonly type;
    private readonly placeholder;
    private readonly disableDate;
    private readonly onConfirm;
    private readonly selectedDate;
    private date1;
    private date2;
    private tempdate1;
    private tempdate2;
    private multipleDates;
    private readonly id;
    private show;
    private readonly eventList;
    private $t;
    private targetDom;
    private $container;
    private selectedMultiple;
    timepicker1: TimePicker;
    timepicker2: TimePicker;
    private removeClickEvent;
    private removeMoveEvent;
    constructor(targetDom: any, options: any, onConfirm: any);
    private init;
    private initTargetDom;
    resetDate(startTime: any, endTime: any): void;
    private rendPicker;
    resetCurrentTime(startTime?: string, endTime?: string): void;
    updateCurrentTime(num: any): void;
    private initTimePicker;
    private initCallback;
    private addTargetEvent;
    private changeShowStatus;
    private addPosEvent;
    private setPosition;
    private rendHoverStyle;
    setDate(): void;
    private rendOtherDateList;
    addEvent(): void;
    private autoConfirm;
    private setCurClass;
    private correctDate;
    setCurrentTime(date2: any, _isinit?: boolean): void;
    setCurrentDay(): void;
    setCurrentClass(): void;
    cleardate(type?: string): void;
    currentdate(): void;
    confirm(clear?: boolean, isFirst?: boolean): void;
    private fillInput;
    private rendWeekNum;
    private getWeekNumList;
    private rendMonth;
    private getMonthList;
    private rendYears;
    private getYearList;
    private getDateCont;
    private rendDatePicker;
    private geneShortList;
    private _getDaysNum;
    private geneDateList;
    private checkDisable;
    private _rendYearHtml;
    private _rendDayHtml;
    private is_leap;
    private trigger;
    private on;
    private getRandomString;
    private _setData;
    watch(key: any, callback: any): void;
    private setTodayDot;
    destroy(): void;
    format(date: any, format: any): string;
}
export default DatePicker;
