import TimePicker from './TimePicker';
export declare class DatePicker {
    private readonly option;
    private readonly type;
    private readonly placeholder;
    private readonly disableDate;
    private readonly onConfirm;
    private readonly selectedDate;
    private date1;
    private date2;
    private tempdate1;
    private tempdate2;
    private multipleDates;
    private readonly id;
    private show;
    private readonly eventList;
    private $t;
    private targetDom;
    private $container;
    private selectedMultiple;
    timepicker1: TimePicker;
    timepicker2: TimePicker;
    private removeClickEvent;
    private removeMoveEvent;
    constructor(targetDom: any, options: any, onConfirm: any);
    init(): void;
    initTargetDom(targetDom: any): void;
    resetDate(startTime: any, endTime: any): void;
    rendPicker(): void;
    resetCurrentTime(startTime?: string, endTime?: string): void;
    updateCurrentTime(num: any): void;
    initTimePicker(): void;
    initCallback(): void;
    addTargetEvent(): void;
    changeShowStatus(hide?: boolean): void;
    addPosEvent(): void;
    setPosition(): void;
    rendHoverStyle($t?: any): void;
    setDate(): void;
    rendOtherDateList(otherdatenum: any): void;
    addEvent(): void;
    autoConfirm(el?: HTMLElement): void;
    setCurClass($t: any): void;
    correctDate(date1: any): any;
    setCurrentTime(date2: any, _isinit?: boolean): void;
    setCurrentDay(): void;
    setCurrentClass(): void;
    cleardate(type?: string): void;
    currentdate(): void;
    confirm(clear?: boolean, isFirst?: boolean): void;
    fillInput(showstrStart: any, showstrEnd: any): void;
    rendWeekNum(datenum: any): void;
    getWeekNumList(datenum: any): string;
    rendMonth(datenum: any): void;
    getMonthList(datenum: any): string;
    rendYears(datenum: any): void;
    getYearList(datenum: any): string;
    getDateCont(): string;
    rendDatePicker(): void;
    geneShortList(): void;
    _getDaysNum(date: any): number;
    geneDateList(curdate: any, $cont: any): void;
    checkDisable(date: any, dir: any, type: any, unit?: string): boolean;
    _rendYearHtml(date: any, $cont: any): void;
    _rendDayHtml(datelist: any, $cont: any, year: any): void;
    is_leap(year: any): 1 | 0;
    trigger(type: any, data: any): void;
    on(type: any, func: any): void;
    getRandomString(len?: number): string;
    _setData(_key: any, $watch: any): void;
    watch(key: any, callback: any): void;
    setTodayDot(type: any): void;
    destroy(): void;
    format(date: any, format: any): string;
}
export default DatePicker;
