import IceCreamSquare from './ice-cream-square';
import Lollipop from './lollipop';
import PotatoStrips from './potato-strips';
import MilkTea from './milk-tea';
import IceDrink from './ice-drink';
import IceTea from './ice-tea';
import Coffee from './coffee';
import Orange from './orange';
import Pear from './pear';
import Apple from './apple';
import Cherry from './cherry';
import Watermelon from './watermelon';
import Grape from './grape';
import Refrigerator from './refrigerator';
import GobletSquareFull from './goblet-square-full';
import GobletSquare from './goblet-square';
import GobletFull from './goblet-full';
import Goblet from './goblet';
import ColdDrink from './cold-drink';
import CoffeeCup from './coffee-cup';
import WaterCup from './water-cup';
import HotWater from './hot-water';
import IceCream from './ice-cream';
import Dessert from './dessert';
import Sugar from './sugar';
import Tableware from './tableware';
import Burger from './burger';
import KnifeFork from './knife-fork';
import ForkSpoon from './fork-spoon';
import Chicken from './chicken';
import Food from './food';
import Dish1 from './dish-1';
import Dish from './dish';
import RefreshLeft from './refresh-left';
import RefreshRight from './refresh-right';
import WarningOutline from './warning-outline';
import Setting from './setting';
import PhoneOutline from './phone-outline';
import MoreOutline from './more-outline';
import Finished from './finished';
import View from './view';
import Loading from './loading';
import Refresh from './refresh';
import Rank from './rank';
import Sort from './sort';
import MobilePhone from './mobile-phone';
import Service from './service';
import Sell from './sell';
import SoldOut from './sold-out';
import Delete from './delete';
import Minus from './minus';
import Plus from './plus';
import Check from './check';
import Close from './close';
import DArrowRight from './d-arrow-right';
import DArrowLeft from './d-arrow-left';
import ArrowLeft from './arrow-left';
import ArrowDown from './arrow-down';
import ArrowRight from './arrow-right';
import ArrowUp from './arrow-up';
import Key from './key';
import User from './user';
import Unlock from './unlock';
import Lock from './lock';
import Top from './top';
import TopRight from './top-right';
import TopLeft from './top-left';
import Right from './right';
import Back from './back';
import Bottom from './bottom';
import BottomRight from './bottom-right';
import BottomLeft from './bottom-left';
import MoonNight from './moon-night';
import Moon from './moon';
import CloudyAndSunny from './cloudy-and-sunny';
import PartlyCloudy from './partly-cloudy';
import Cloudy from './cloudy';
import Sunny from './sunny';
import Sunset from './sunset';
import Sunrise1 from './sunrise-1';
import Sunrise from './sunrise';
import HeavyRain from './heavy-rain';
import Lightning from './lightning';
import LightRain from './light-rain';
import WindPower from './wind-power';
import Watch from './watch';
import Watch1 from './watch-1';
import Timer from './timer';
import AlarmClock from './alarm-clock';
import MapLocation from './map-location';
import DeleteLocation from './delete-location';
import AddLocation from './add-location';
import LocationInformation from './location-information';
import LocationOutline from './location-outline';
import Place from './place';
import Discover from './discover';
import FirstAidKit from './first-aid-kit';
import Trophy1 from './trophy-1';
import Trophy from './trophy';
import Medal from './medal';
import Medal1 from './medal-1';
import Stopwatch from './stopwatch';
import Mic from './mic';
import Baseball from './baseball';
import Soccer from './soccer';
import Football from './football';
import Basketball from './basketball';
import StarOff from './star-off';
import CopyDocument from './copy-document';
import FullScreen from './full-screen';
import SwitchButton from './switch-button';
import Aim from './aim';
import Crop from './crop';
import Odometer from './odometer';
import Time from './time';
import CircleCheck from './circle-check';
import RemoveOutline from './remove-outline';
import CirclePlusOutline from './circle-plus-outline';
import Bangzhu from './bangzhu';
import Bell from './bell';
import CloseNotification from './close-notification';
import Microphone from './microphone';
import TurnOffMicrophone from './turn-off-microphone';
import Position from './position';
import Postcard from './postcard';
import Message from './message';
import ChatLineSquare from './chat-line-square';
import ChatDotSquare from './chat-dot-square';
import ChatDotRound from './chat-dot-round';
import ChatSquare from './chat-square';
import ChatLineRound from './chat-line-round';
import ChatRound from './chat-round';
import SetUp from './set-up';
import TurnOff from './turn-off';
import Open from './open';
import Connection from './connection';
import Link from './link';
import Cpu from './cpu';
import Thumb from './thumb';
import Female from './female';
import Male from './male';
import Guide from './guide';
import Help from './help';
import News from './news';
import Ship from './ship';
import Truck from './truck';
import Bicycle from './bicycle';
import PriceTag from './price-tag';
import Discount from './discount';
import Wallet from './wallet';
import Coin from './coin';
import Money from './money';
import BankCard from './bank-card';
import Box from './box';
import Present from './present';
import ShoppingBag2 from './shopping-bag-2';
import ShoppingBag1 from './shopping-bag-1';
import ShoppingCart2 from './shopping-cart-2';
import ShoppingCart1 from './shopping-cart-1';
import ShoppingCartFull from './shopping-cart-full';
import Smoking from './smoking';
import NoSmoking from './no-smoking';
import House from './house';
import TableLamp from './table-lamp';
import School from './school';
import OfficeBuilding from './office-building';
import ToiletPaper from './toilet-paper';
import Notebook2 from './notebook-2';
import Notebook1 from './notebook-1';
import Files from './files';
import Collection from './collection';
import Receiving from './receiving';
import PictureOutline from './picture-outline';
import PictureOutlineRound from './picture-outline-round';
import Suitcase1 from './suitcase-1';
import Suitcase from './suitcase';
import Film from './film';
import EditOutline from './edit-outline';
import CollectionTag from './collection-tag';
import DataAnalysis from './data-analysis';
import PieChart from './pie-chart';
import DataBoard from './data-board';
import Reading from './reading';
import MagicStick from './magic-stick';
import Coordinate from './coordinate';
import Mouse from './mouse';
import DataLine from './data-line';
import Brush from './brush';
import Headset from './headset';
import Umbrella from './umbrella';
import Scissors from './scissors';
import VideoCamera from './video-camera';
import Mobile from './mobile';
import Attract from './attract';
import Monitor from './monitor';
import ZoomOut from './zoom-out';
import ZoomIn from './zoom-in';
import Search from './search';
import Camera from './camera';
import TakeawayBox from './takeaway-box';
import Upload2 from './upload2';
import Download from './download';
import Paperclip from './paperclip';
import Printer from './printer';
import DocumentAdd from './document-add';
import Document from './document';
import DocumentChecked from './document-checked';
import DocumentCopy from './document-copy';
import DocumentDelete from './document-delete';
import DocumentRemove from './document-remove';
import Tickets from './tickets';
import FolderChecked from './folder-checked';
import FolderDelete from './folder-delete';
import FolderRemove from './folder-remove';
import FolderAdd from './folder-add';
import FolderOpened from './folder-opened';
import Folder from './folder';
import Edit from './edit';
import CircleClose from './circle-close';
import Date from './date';
import CaretTop from './caret-top';
import CaretBottom from './caret-bottom';
import CaretRight from './caret-right';
import CaretLeft from './caret-left';
import Share from './share';
import More from './more';
import Phone from './phone';
import VideoCameraSolid from './video-camera-solid';
import StarOn from './star-on';
import Menu from './menu';
import MessageSolid from './message-solid';
import DCaret from './d-caret';
import CameraSolid from './camera-solid';
import Success from './success';
import Error from './error';
import Location from './location';
import Picture from './picture';
import CirclePlus from './circle-plus';
import Info from './info';
import Remove from './remove';
import Warning from './warning';
import Question from './question';
import UserSolid from './user-solid';
import SGrid from './s-grid';
import SCheck from './s-check';
import SData from './s-data';
import SFold from './s-fold';
import SOpportunity from './s-opportunity';
import SCustom from './s-custom';
import STools from './s-tools';
import SClaim from './s-claim';
import SFinance from './s-finance';
import SComment from './s-comment';
import SFlag from './s-flag';
import SMarketing from './s-marketing';
import SGoods from './s-goods';
import SHelp from './s-help';
import SShop from './s-shop';
import SOpen from './s-open';
import SManagement from './s-management';
import STicket from './s-ticket';
import SRelease from './s-release';
import SHome from './s-home';
import SPromotion from './s-promotion';
import SOperation from './s-operation';
import SUnfold from './s-unfold';
import SPlatform from './s-platform';
import SOrder from './s-order';
import SCooperation from './s-cooperation';
import VideoPlay from './video-play';
import VideoPause from './video-pause';
import Goods from './goods';
import Upload from './upload';
import SortDown from './sort-down';
import SortUp from './sort-up';
import CScaleToOriginal from './c-scale-to-original';
import Eleme from './eleme';
import DeleteSolid from './delete-solid';
import PlatformEleme from './platform-eleme';
import WuIcon from './wu-icon';
declare const _default: {
    WuIcon: typeof WuIcon;
    IceCreamSquare: typeof IceCreamSquare;
    Lollipop: typeof Lollipop;
    PotatoStrips: typeof PotatoStrips;
    MilkTea: typeof MilkTea;
    IceDrink: typeof IceDrink;
    IceTea: typeof IceTea;
    Coffee: typeof Coffee;
    Orange: typeof Orange;
    Pear: typeof Pear;
    Apple: typeof Apple;
    Cherry: typeof Cherry;
    Watermelon: typeof Watermelon;
    Grape: typeof Grape;
    Refrigerator: typeof Refrigerator;
    GobletSquareFull: typeof GobletSquareFull;
    GobletSquare: typeof GobletSquare;
    GobletFull: typeof GobletFull;
    Goblet: typeof Goblet;
    ColdDrink: typeof ColdDrink;
    CoffeeCup: typeof CoffeeCup;
    WaterCup: typeof WaterCup;
    HotWater: typeof HotWater;
    IceCream: typeof IceCream;
    Dessert: typeof Dessert;
    Sugar: typeof Sugar;
    Tableware: typeof Tableware;
    Burger: typeof Burger;
    KnifeFork: typeof KnifeFork;
    ForkSpoon: typeof ForkSpoon;
    Chicken: typeof Chicken;
    Food: typeof Food;
    Dish1: typeof Dish1;
    Dish: typeof Dish;
    RefreshLeft: typeof RefreshLeft;
    RefreshRight: typeof RefreshRight;
    WarningOutline: typeof WarningOutline;
    Setting: typeof Setting;
    PhoneOutline: typeof PhoneOutline;
    MoreOutline: typeof MoreOutline;
    Finished: typeof Finished;
    View: typeof View;
    Loading: typeof Loading;
    Refresh: typeof Refresh;
    Rank: typeof Rank;
    Sort: typeof Sort;
    MobilePhone: typeof MobilePhone;
    Service: typeof Service;
    Sell: typeof Sell;
    SoldOut: typeof SoldOut;
    Delete: typeof Delete;
    Minus: typeof Minus;
    Plus: typeof Plus;
    Check: typeof Check;
    Close: typeof Close;
    DArrowRight: typeof DArrowRight;
    DArrowLeft: typeof DArrowLeft;
    ArrowLeft: typeof ArrowLeft;
    ArrowDown: typeof ArrowDown;
    ArrowRight: typeof ArrowRight;
    ArrowUp: typeof ArrowUp;
    Key: typeof Key;
    User: typeof User;
    Unlock: typeof Unlock;
    Lock: typeof Lock;
    Top: typeof Top;
    TopRight: typeof TopRight;
    TopLeft: typeof TopLeft;
    Right: typeof Right;
    Back: typeof Back;
    Bottom: typeof Bottom;
    BottomRight: typeof BottomRight;
    BottomLeft: typeof BottomLeft;
    MoonNight: typeof MoonNight;
    Moon: typeof Moon;
    CloudyAndSunny: typeof CloudyAndSunny;
    PartlyCloudy: typeof PartlyCloudy;
    Cloudy: typeof Cloudy;
    Sunny: typeof Sunny;
    Sunset: typeof Sunset;
    Sunrise1: typeof Sunrise1;
    Sunrise: typeof Sunrise;
    HeavyRain: typeof HeavyRain;
    Lightning: typeof Lightning;
    LightRain: typeof LightRain;
    WindPower: typeof WindPower;
    Watch: typeof Watch;
    Watch1: typeof Watch1;
    Timer: typeof Timer;
    AlarmClock: typeof AlarmClock;
    MapLocation: typeof MapLocation;
    DeleteLocation: typeof DeleteLocation;
    AddLocation: typeof AddLocation;
    LocationInformation: typeof LocationInformation;
    LocationOutline: typeof LocationOutline;
    Place: typeof Place;
    Discover: typeof Discover;
    FirstAidKit: typeof FirstAidKit;
    Trophy1: typeof Trophy1;
    Trophy: typeof Trophy;
    Medal: typeof Medal;
    Medal1: typeof Medal1;
    Stopwatch: typeof Stopwatch;
    Mic: typeof Mic;
    Baseball: typeof Baseball;
    Soccer: typeof Soccer;
    Football: typeof Football;
    Basketball: typeof Basketball;
    StarOff: typeof StarOff;
    CopyDocument: typeof CopyDocument;
    FullScreen: typeof FullScreen;
    SwitchButton: typeof SwitchButton;
    Aim: typeof Aim;
    Crop: typeof Crop;
    Odometer: typeof Odometer;
    Time: typeof Time;
    CircleCheck: typeof CircleCheck;
    RemoveOutline: typeof RemoveOutline;
    CirclePlusOutline: typeof CirclePlusOutline;
    Bangzhu: typeof Bangzhu;
    Bell: typeof Bell;
    CloseNotification: typeof CloseNotification;
    Microphone: typeof Microphone;
    TurnOffMicrophone: typeof TurnOffMicrophone;
    Position: typeof Position;
    Postcard: typeof Postcard;
    Message: typeof Message;
    ChatLineSquare: typeof ChatLineSquare;
    ChatDotSquare: typeof ChatDotSquare;
    ChatDotRound: typeof ChatDotRound;
    ChatSquare: typeof ChatSquare;
    ChatLineRound: typeof ChatLineRound;
    ChatRound: typeof ChatRound;
    SetUp: typeof SetUp;
    TurnOff: typeof TurnOff;
    Open: typeof Open;
    Connection: typeof Connection;
    Link: typeof Link;
    Cpu: typeof Cpu;
    Thumb: typeof Thumb;
    Female: typeof Female;
    Male: typeof Male;
    Guide: typeof Guide;
    Help: typeof Help;
    News: typeof News;
    Ship: typeof Ship;
    Truck: typeof Truck;
    Bicycle: typeof Bicycle;
    PriceTag: typeof PriceTag;
    Discount: typeof Discount;
    Wallet: typeof Wallet;
    Coin: typeof Coin;
    Money: typeof Money;
    BankCard: typeof BankCard;
    Box: typeof Box;
    Present: typeof Present;
    ShoppingBag2: typeof ShoppingBag2;
    ShoppingBag1: typeof ShoppingBag1;
    ShoppingCart2: typeof ShoppingCart2;
    ShoppingCart1: typeof ShoppingCart1;
    ShoppingCartFull: typeof ShoppingCartFull;
    Smoking: typeof Smoking;
    NoSmoking: typeof NoSmoking;
    House: typeof House;
    TableLamp: typeof TableLamp;
    School: typeof School;
    OfficeBuilding: typeof OfficeBuilding;
    ToiletPaper: typeof ToiletPaper;
    Notebook2: typeof Notebook2;
    Notebook1: typeof Notebook1;
    Files: typeof Files;
    Collection: typeof Collection;
    Receiving: typeof Receiving;
    PictureOutline: typeof PictureOutline;
    PictureOutlineRound: typeof PictureOutlineRound;
    Suitcase1: typeof Suitcase1;
    Suitcase: typeof Suitcase;
    Film: typeof Film;
    EditOutline: typeof EditOutline;
    CollectionTag: typeof CollectionTag;
    DataAnalysis: typeof DataAnalysis;
    PieChart: typeof PieChart;
    DataBoard: typeof DataBoard;
    Reading: typeof Reading;
    MagicStick: typeof MagicStick;
    Coordinate: typeof Coordinate;
    Mouse: typeof Mouse;
    DataLine: typeof DataLine;
    Brush: typeof Brush;
    Headset: typeof Headset;
    Umbrella: typeof Umbrella;
    Scissors: typeof Scissors;
    VideoCamera: typeof VideoCamera;
    Mobile: typeof Mobile;
    Attract: typeof Attract;
    Monitor: typeof Monitor;
    ZoomOut: typeof ZoomOut;
    ZoomIn: typeof ZoomIn;
    Search: typeof Search;
    Camera: typeof Camera;
    TakeawayBox: typeof TakeawayBox;
    Upload2: typeof Upload2;
    Download: typeof Download;
    Paperclip: typeof Paperclip;
    Printer: typeof Printer;
    DocumentAdd: typeof DocumentAdd;
    Document: typeof Document;
    DocumentChecked: typeof DocumentChecked;
    DocumentCopy: typeof DocumentCopy;
    DocumentDelete: typeof DocumentDelete;
    DocumentRemove: typeof DocumentRemove;
    Tickets: typeof Tickets;
    FolderChecked: typeof FolderChecked;
    FolderDelete: typeof FolderDelete;
    FolderRemove: typeof FolderRemove;
    FolderAdd: typeof FolderAdd;
    FolderOpened: typeof FolderOpened;
    Folder: typeof Folder;
    Edit: typeof Edit;
    CircleClose: typeof CircleClose;
    Date: typeof Date;
    CaretTop: typeof CaretTop;
    CaretBottom: typeof CaretBottom;
    CaretRight: typeof CaretRight;
    CaretLeft: typeof CaretLeft;
    Share: typeof Share;
    More: typeof More;
    Phone: typeof Phone;
    VideoCameraSolid: typeof VideoCameraSolid;
    StarOn: typeof StarOn;
    Menu: typeof Menu;
    MessageSolid: typeof MessageSolid;
    DCaret: typeof DCaret;
    CameraSolid: typeof CameraSolid;
    Success: typeof Success;
    Error: typeof Error;
    Location: typeof Location;
    Picture: typeof Picture;
    CirclePlus: typeof CirclePlus;
    Info: typeof Info;
    Remove: typeof Remove;
    Warning: typeof Warning;
    Question: typeof Question;
    UserSolid: typeof UserSolid;
    SGrid: typeof SGrid;
    SCheck: typeof SCheck;
    SData: typeof SData;
    SFold: typeof SFold;
    SOpportunity: typeof SOpportunity;
    SCustom: typeof SCustom;
    STools: typeof STools;
    SClaim: typeof SClaim;
    SFinance: typeof SFinance;
    SComment: typeof SComment;
    SFlag: typeof SFlag;
    SMarketing: typeof SMarketing;
    SGoods: typeof SGoods;
    SHelp: typeof SHelp;
    SShop: typeof SShop;
    SOpen: typeof SOpen;
    SManagement: typeof SManagement;
    STicket: typeof STicket;
    SRelease: typeof SRelease;
    SHome: typeof SHome;
    SPromotion: typeof SPromotion;
    SOperation: typeof SOperation;
    SUnfold: typeof SUnfold;
    SPlatform: typeof SPlatform;
    SOrder: typeof SOrder;
    SCooperation: typeof SCooperation;
    VideoPlay: typeof VideoPlay;
    VideoPause: typeof VideoPause;
    Goods: typeof Goods;
    Upload: typeof Upload;
    SortDown: typeof SortDown;
    SortUp: typeof SortUp;
    CScaleToOriginal: typeof CScaleToOriginal;
    Eleme: typeof Eleme;
    DeleteSolid: typeof DeleteSolid;
    PlatformEleme: typeof PlatformEleme;
};
export default _default;
